<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>DirectInternetMethod</AssemblyName><RootNamespace>DirectInternetMethod</RootNamespace><ApplicationIcon>..\app\DirectInternetMethod.ico</ApplicationIcon><Version>1.5.0</Version><FileVersion>1.5.0.0</FileVersion><AssemblyVersion>1.5.0.0</AssemblyVersion><Product>Direct Internet Method</Product></PropertyGroup><ItemGroup><Resource Include="..\app\DirectInternetMethod.ico"><Link>DirectInternetMethod.ico</Link></Resource></ItemGroup></Project>