<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DirectInternetMethod.Service</AssemblyName>
    <RootNamespace>DirectInternetMethod.Service</RootNamespace>
    <ApplicationIcon>..\app\DirectInternetMethod.ico</ApplicationIcon>
    <Version>1.5.0</Version>
    <FileVersion>1.5.0.0</FileVersion>
    <AssemblyVersion>1.5.0.0</AssemblyVersion>
    <Product>Direct Internet Method Service</Product>
  </PropertyGroup>
</Project>